apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: microservices
  labels:
    app: auth-service
spec:
  type: ClusterIP
  selector:
    app: auth-service
  ports:
  - port: 3002
    targetPort: 3002
    protocol: TCP
    name: http
  sessionAffinity: None 