apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: microservices
  labels:
    app: notification-service
spec:
  type: ClusterIP
  selector:
    app: notification-service
  ports:
  - port: 3003
    targetPort: 3003
    protocol: TCP
    name: http
  sessionAffinity: None 